name: Deploy Backend API

on:
    push:
        branches: [main, staging]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - run: npm test

    docker-build-push:
        needs: build-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              run: docker build -t mydockerhub/backend-api:${{ github.sha }} .
            - name: Push Docker image
              run: docker push mydockerhub/backend-api:${{ github.sha }}

    deploy:
        needs: docker-build-push
        runs-on: ubuntu-latest
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd /path/to/deployment/scripts
                      bash deploy.sh ${{ github.sha }}
